apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  loadBalancerIP: 9.163.65.185
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      