- name: Configurar Nginx en Kubernetes
  hosts: localhost
  become: yes
  tasks:
    - name: Copiar archivos de configuración
      copy:
        src: ./nginx-deployment.yaml
        dest: /home/azureuser/terraform/aks/nginx-deployment.yaml

    - name: Aplicar configuración de Kubernetes
      shell: |
        kubectl apply -f /home/azureuser/terraform/aks/nginx-deployment.yaml
        kubectl apply -f /home/azureuser/terraform/aks/nginx-service.yaml
